### PR TITLE
[Issue-62]: add packages onion-dt-overlay-spi

### PR DESCRIPTION
**Pull request by jempatel**

### CODE REVIEW

**Comment by greenbreakfast** [comment]
@jempatel Does this need to be updated after the latest commit to https://github.com/OnionIoT/OpenWRT-Packages/pull/68 ?

cc https://github.com/OnionIoT/OpenWRT-Packages/issues/62

**Comment by jempatel** [comment]
> @jempatel Does this need to be updated after the latest commit to https://github.com/OnionIoT/OpenWRT-Packages/pull/68 ?

New changes are still in testimg.  I will comment here once testing is done.

**Comment by greenbreakfast** [comment]
@jempatel thanks. I'll hold off on merging https://github.com/OnionIoT/openwrt-buildsystem-wrapper/pull/20, https://github.com/OnionIoT/OpenWRT-Packages/pull/68, and this PR until you give the word

**Comment by jempatel** [comment]
> @jempatel thanks. I'll hold off on merging [OnionIoT/openwrt-buildsystem-wrapper#20](https://github.com/OnionIoT/openwrt-buildsystem-wrapper/pull/20), [OnionIoT/OpenWRT-Packages#68](https://github.com/OnionIoT/OpenWRT-Packages/pull/68), and this PR until you give the word

Changes are tested, with documentation.

**Pull request merged**
